In [1]:
import theano

DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/Allen/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpowwiwp/265abc51f7c376c224983485238ff1a5.lib and object C:/Users/Allen/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpowwiwp/265abc51f7c376c224983485238ff1a5.exp

Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled, cuDNN 4007)


In [2]:
import theano.tensor as T

In [3]:
x = T.dmatrix('x')
y = T.dmatrix('y')
data = theano.shared(numpy.zeros([2, 2], 'd'), name = 'data')

NameError: name 'numpy' is not defined

In [4]:
import numpy
x = T.dmatrix('x')
y = T.dmatrix('y')
data = theano.shared(numpy.zeros([2, 2], 'd'), name = 'data')

In [10]:
data.eval()

array([[ 0.,  0.],
       [ 0.,  0.]])

In [11]:
y = y + x * x.T
add_s  = theano.function([x, y], y)

UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: x.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

In [12]:
z = y + x * x.T
add_s  = theano.function([x, y], z)

In [13]:
val1 = numpy.array([[1,2],[3,4]], 'd')

In [14]:
add_s(data, val1)

TypeError: ('Bad input argument to theano function with name "<ipython-input-12-9a03b3377961>:2"  at index 0(0-based)', 'Expected an array-like object, but found a Variable: maybe you are trying to call a function on a (possibly shared) variable instead of a numeric array?')

In [15]:
val1.eval()

AttributeError: 'numpy.ndarray' object has no attribute 'eval'

In [16]:
add_s(val1, val1)

array([[  2.,   8.],
       [  9.,  20.]])

In [17]:
data += add_s(val1, val1)

In [18]:
data


Elemwise{add,no_inplace}.0

In [19]:
data.eval()

array([[  2.,   8.],
       [  9.,  20.]])

In [20]:
data += add_s(val1, val1)

In [21]:
data.eval()

array([[  4.,  16.],
       [ 18.,  40.]])

In [22]:
data.eval()

array([[  4.,  16.],
       [ 18.,  40.]])

In [23]:
incrs = theano.function([x], data, update=[(data, data + x * x.T)])

TypeError: function() got an unexpected keyword argument 'update'

In [24]:
incrs = theano.function([x], data, updates=[(data, data + x * x.T)])

TypeError: ('update target must be a SharedVariable', Elemwise{add,no_inplace}.0)

In [25]:
data = theano.shared(data)

TypeError: Shared variable constructor needs numeric values and not symbolic variables.

In [26]:
data = theano.shared(numpy.zeros([2, 2]))

In [27]:
data

<TensorType(float64, matrix)>

In [28]:
incrs = theano.function([x], data, updates=[(data, data + x * x.T)])

In [29]:
val1.eval()

AttributeError: 'numpy.ndarray' object has no attribute 'eval'

In [30]:
val1

array([[ 1.,  2.],
       [ 3.,  4.]])

In [31]:
incs(val1)

NameError: name 'incs' is not defined

In [32]:
incrs(val1)

array([[ 0.,  0.],
       [ 0.,  0.]])

In [33]:
incrs(val1)

array([[  1.,   6.],
       [  6.,  16.]])

In [34]:
incrs(val1)

array([[  2.,  12.],
       [ 12.,  32.]])

In [35]:
incrs(val1)

array([[  3.,  18.],
       [ 18.,  48.]])

In [1]:
import theano
import theano.tensor as T

DEBUG: nvcc STDOUT mod.cu
   Creating library C:/Users/Allen/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpyral8a/265abc51f7c376c224983485238ff1a5.lib and object C:/Users/Allen/AppData/Local/Theano/compiledir_Windows-10-10.0.10586-Intel64_Family_6_Model_94_Stepping_3_GenuineIntel-2.7.11-64/tmpyral8a/265abc51f7c376c224983485238ff1a5.exp

Using gpu device 0: GeForce GTX 750 Ti (CNMeM is disabled, cuDNN 4007)


In [2]:
x = T.dmatrix('x')
import numpy

In [3]:
z = T.sum(x, 0)

In [4]:
f = theano.function([x], z)

In [5]:
f([[1,2],[3,4]])

array([ 4.,  6.])

In [6]:
z1 = T.sum(x, 0) / (x.shape[0])

In [7]:
f1 = theano.function([x], z1)

In [8]:
f1([[1,2],[3,4]])

array([ 2.,  3.])

In [9]:
d = T.ivector()

In [10]:
f = theano.function([d], d)

In [11]:
f(4)

TypeError: ('Bad input argument to theano function with name "<ipython-input-10-1163f9132f29>:1"  at index 0(0-based)', 'Wrong number of dimensions: expected 1, got 0 with shape ().')

In [12]:
d = T.iscalar()

In [13]:
f = theano.function([d], d)
f(4)

array(4)

In [14]:
x

x

In [15]:
f = theano.function([d, x], d + x.shaep[0])

AttributeError: 'TensorVariable' object has no attribute 'shaep'

In [16]:
f = theano.function([d, x], d + x.shape[0])

In [17]:
f(4, numpy.zeros([3,3]))


array(7L, dtype=int64)

In [18]:
f = theano.function([d, x], d * x)

In [19]:
f(4, numpy.zeros([3,3]))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
f(4, numpy.ones([3,3]))

array([[ 4.,  4.,  4.],
       [ 4.,  4.,  4.],
       [ 4.,  4.,  4.]])

In [21]:
mean = theano.shared(numpy.zeros([3, 1]))

In [22]:
mean.eval()

array([[ 0.],
       [ 0.],
       [ 0.]])

In [23]:
mean = theano.shared(numpy.zeros([1, 3]))
mean.eval()

array([[ 0.,  0.,  0.]])

In [24]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) + mean)])

UnusedInputError: theano.function was asked to create a function computing outputs given certain inputs, but the provided input variable at index 0 is not part of the computational graph needed to compute the outputs: <TensorType(int32, scalar)>.
To make this error into a warning, you can pass the parameter on_unused_input='warn' to theano.function. To disable it completely, use on_unused_input='ignore'.

In [25]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) + mean * d)])

In [26]:
val = numpy.array([[1, 1, 1],[2, 2, 2], [3, 3,3 ]])


In [27]:
val

array([[1, 1, 1],
       [2, 2, 2],
       [3, 3, 3]])

In [28]:
f(3, val)

array([[ 0.,  0.,  0.]])

In [29]:
f(3, val)

array([[ 6.,  6.,  6.]])

In [30]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) / (d + x.shape[0]) + d * mean / (d + x.shape[0])])

SyntaxError: invalid syntax (<ipython-input-30-05c086177ff4>, line 1)

In [31]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) / (d + x.shape[0]) + d * mean / (d + x.shape[0]))])

In [32]:
f = theano.function([x], data, updates = [(data, data + x.T * x)])

NameError: name 'data' is not defined

In [33]:
data = theano.shared(numpy.zeros([3, 3]))

In [34]:
f = theano.function([x], data, updates = [(data, data + x.T * x)])

In [35]:
x = numpy.ones([5, 3])

In [36]:
x.eval()

AttributeError: 'numpy.ndarray' object has no attribute 'eval'

In [37]:
x


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
f(x)

ValueError: Input dimension mis-match. (input[0].shape[0] = 3, input[2].shape[0] = 5)
Apply node that caused the error: Elemwise{Composite{(i0 + (i1 * i2))}}(<TensorType(float64, matrix)>, x.T, x)
Toposort index: 1
Inputs types: [TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(3L, 3L), (3L, 5L), (5L, 3L)]
Inputs strides: [(24L, 8L), (8L, 24L), (24L, 8L)]
Inputs values: ['not shown', 'not shown', 'not shown']
Outputs clients: [['output']]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

In [39]:
x * numpy.transpose(x)

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [40]:
numpy.transpose(x) * x

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

In [41]:
x * x


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [42]:
x * x.T

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [43]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) / (d + x.shape[0]) + d * mean / (d + x.shape[0]))])

TypeError: Unknown parameter type: <type 'numpy.ndarray'>

In [44]:
 T.sum(x, 0)

Sum{axis=[0], acc_dtype=float64}.0

In [45]:
x


array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [46]:
x.dtype

dtype('float64')

In [47]:
x = numpy.ones([5, 3], dtype = 'float32')

In [48]:
 T.sum(x, 0)

Sum{axis=[0], acc_dtype=float64}.0

In [49]:
x.dtype

dtype('float32')

In [50]:
f = theano.function([d, x], mean, updates=[(mean, T.sum(x, 0) / (d + x.shape[0]) + mean)])

TypeError: Unknown parameter type: <type 'numpy.ndarray'>